# Generated by Django 5.1.3 on 2024-11-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("electronics", "Electronics"),
                            ("clothing", "Clothing"),
                            ("furniture", "Furniture"),
                            ("appliances", "Appliances"),
                            ("books", "Books"),
                            ("toys", "Toys"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("stock", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="providers.providers",
                    ),
                ),
            ],
        ),
    ]
